### ISSUE TITLE
python import failing with undefined symbol

### ISSUE THREAD

**Issue by moleary** [BLLIP/bllip-parser#59]
Hi, 

I've installed and re-installed bllipparser a few times on Ubuntu Xenial 16.04 and I keep getting the same import errors in python (anaconda). Has anyone else seen this issue? Here is my attempt at an import:

Python 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import bllipparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/bllipparser/__init__.py", line 399, in <module>
    from .RerankingParser import RerankingParser, Tree, Sentence, tokenize
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/bllipparser/RerankingParser.py", line 19, in <module>
    from . import CharniakParser as parser
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/bllipparser/CharniakParser.py", line 28, in <module>
    _CharniakParser = swig_import_helper()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/bllipparser/CharniakParser.py", line 24, in swig_import_helper
    _mod = imp.load_module('_CharniakParser', fp, pathname, description)
ImportError: /home/ubuntu/anaconda2/lib/python2.7/site-packages/bllipparser/_CharniakParser.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

**Comment by dmcc** [comment]
Looks like it might be an Anaconda issue (
https://github.com/stan-dev/pystan/issues/269,
https://github.com/stan-dev/pystan/issues/292). Are you using "pip install"
or "conda install"?

**Comment by moleary** [comment]
That's what it was. It works fine with the standard python install. Thanks for the help!
