### ISSUE TITLE
Error downloading model (501 Not Implemented)

### ISSUE THREAD

**Issue by liziming5353** [BLLIP/bllip-parser#63]
Followed the instructions on the home page. But there's a problem with the model download process.

When i run wget https://www.dropbox.com/s/ulcfs7my1ifriuu/BLLIP-WSJ-PTB3.tar.bz2?dl=1:

Fetching model: WSJ-PTB3 from https://www.dropbox.com/s/ulcfs7my1ifriuu/BLLIP-WSJ-PTB3.tar.bz2?dl=1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lzm/.local/lib/python2.7/site-packages/bllipparser/RerankingParser.py", line 897, in fetch_and_load
    verbose)
  File "/home/lzm/.local/lib/python2.7/site-packages/bllipparser/ModelFetcher.py", line 124, in download_and_install_model
    reporthook=status_func)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 101] Network is unreachable

**Comment by dmcc** [comment]
Is this still an issue for you? I tried with a fresh client and couldn't
reproduce.

Also, are you saying that the wget command works but running things like
"python -m bllipparser WSJ-PTB3" doesn't?

**Comment by MrTree0-0** [comment]
Use a VPN

**Comment by liutaonuist** [comment]
I encountered the same mistake. How did you solve it?

**Comment by liutaonuist** [comment]
> Followed the instructions on the home page. But there's a problem with the model download process.
> 
> When i run wget https://www.dropbox.com/s/ulcfs7my1ifriuu/BLLIP-WSJ-PTB3.tar.bz2?dl=1:
> 
> Fetching model: WSJ-PTB3 from https://www.dropbox.com/s/ulcfs7my1ifriuu/BLLIP-WSJ-PTB3.tar.bz2?dl=1 Traceback (most recent call last): File "", line 1, in File "/home/lzm/.local/lib/python2.7/site-packages/bllipparser/RerankingParser.py", line 897, in fetch_and_load verbose) File "/home/lzm/.local/lib/python2.7/site-packages/bllipparser/ModelFetcher.py", line 124, in download_and_install_model reporthook=status_func) File "/usr/lib/python2.7/urllib.py", line 245, in retrieve fp = self.open(url, data) File "/usr/lib/python2.7/urllib.py", line 213, in open return getattr(self, name)(url) File "/usr/lib/python2.7/urllib.py", line 443, in open_https h.endheaders(data) File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders self._send_output(message_body) File "/usr/lib/python2.7/httplib.py", line 897, in _send_output self.send(msg) File "/usr/lib/python2.7/httplib.py", line 859, in send self.connect() File "/usr/lib/python2.7/httplib.py", line 1270, in connect HTTPConnection.connect(self) File "/usr/lib/python2.7/httplib.py", line 836, in connect self.timeout, self.source_address) File "/usr/lib/python2.7/socket.py", line 575, in create_connection raise err IOError: [Errno socket error] [Errno 101] Network is unreachable

I encountered the same mistake. How did you solve it?
